class Question {
  Question(this.category, this.type, this.difficulty, this.question,
      this.correctAnswer, this.incorrectAnswers);

  String category;
  String type;
  String difficulty;
  String question;
  String correctAnswer;
  List<String> incorrectAnswers;

  static List<Question> questions = [
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "Nintendo started out as a playing card manufacturer.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "The name of the main character of the video game 'The Legend of Zelda', is Zelda.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "The song 'Megalovania' by Toby Fox made its third appearence in the 2015 RPG 'Undertale'.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "The Mann Co. Store from Team Fortress 2 has the slogan 'We hire mercenaries and get in fights'.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "In 'Mario Kart 64', Waluigi is a playable character.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "The first Maxis game to feature the fictional language 'Simlish' was The Sims (2000).",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "Faust is a playable character in 'Guilty Gear Xrd Revelator'.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "hard",
        "In the game 'Melty Blood Actress Again Current Code', you can enter Blood Heat mode in Half Moon style.",
        "False",
        ["True"]),
    Question("Entertainment: Video Games", "boolean", "easy",
        "Luigi is taller than Mario?", "True", ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "Donkey Kong was originally set to be a Popeye arcade game.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "In World of Warcraft lore, Thrall is the original wielder of 'Doomhammer'.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "In Half-Life 2, if you play the zombies' speech in reverse, they actually speak coherent English.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "Minecraft can be played with a virtual reality headset.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "hard",
        "In Undertale, having a 'Fun Value' set to 56-57 will play the 'Wrong Number Song Call'.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "The Sniper's SMG in Team Fortress 2, was originally intended to be the Scout's primary weapon.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "TF2: The Heavy's voice actor, Gary Schwartz, voices the Demoman as well ",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "The main playable character of the 2015 RPG 'Undertale' is a monster.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "hard",
        "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "Ana was added as a new hero for the game Overwatch on July 19th, 2016.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "In the game Dead by Daylight, the killer Michael Myers is refered to as 'The Shape'.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "In Terraria, you can craft the Cell Phone pre-hardmode.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "In Pokémon, Bulbasaur is the only starter pokemon that is a Grass/Poison type.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.",
        "False",
        ["True"]),
    Question("Entertainment: Video Games", "boolean", "medium",
        "In Rocket League, you can play Basketball.", "True", ["False"]),
    Question("Entertainment: Video Games", "boolean", "easy",
        "In Pokémon, Arbok evolves into Seviper.", "False", ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "David Baszucki was a co-founder of ROBLOX Corporation.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "hard",
        "All of these maps were in 'Tom Clancy's Rainbow Six Siege' on its initial release: House, Clubhouse, Border, Consulate.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
        "False",
        ["True"]),
    Question("Entertainment: Video Games", "boolean", "medium",
        "In Portal, the Companion Cube's ARE sentient.", "True", ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "The ADAM collecters in the Bioshock series are known as Little Sisters.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "'Metal Gear Solid 3: Snake Eater' was released in 2004.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "The Fiat Multipla is a drivable car in 'Forza Horizon 3'.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "Several characters in 'Super Mario 64' blink their eyes, including Mario himself.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "'Return to Castle Wolfenstein' was the only game of the Wolfenstein series where you don't play as William 'B.J.' Blazkowicz.",
        "False",
        ["True"]),
    Question("Entertainment: Video Games", "boolean", "easy",
        "Activision created Battlefield 1.", "False", ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "The character that would eventually become Dr. Eggman was considered for the role of Sega's new flagship mascot before Sonic was.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "Hidden in the files for 'Mario Kart Arcade GP' is a picture of the Beslan school hostage crisis.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "'Sonic the Hedgehog 2' originally was going to have a time travel system.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "In 'Need for Speed: Porsche Unleashed', the player can only drive cars manufactured by Porsche.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "hard",
        "In 'Minecraft', gold tools are faster than diamond tools.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "In the game 'Until Dawn' Emily is the only playable character who can be killed by another playable character directly.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "In the video game 'Splatoon', the playable characters were originally going to be rabbits instead of squids.",
        "True",
        ["False"]),
    Question("Entertainment: Video Games", "boolean", "easy",
        "Each piece in Tetris is called a tetris.", "False", ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "hard",
        "The Paradox Interactive game 'Stellaris' was released in 2016.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "hard",
        "In The Witcher 3, the Zoltan Chivay Gwent card can be found under the Hanged Man's Tree.",
        "True",
        ["False"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "easy",
        "In the Monster Hunter Series, it is possible to capture Elder Dragons.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "In the Resident Evil series, Leon S. Kennedy is a member of STARS.",
        "False",
        ["True"]),
    Question(
        "Entertainment: Video Games",
        "boolean",
        "medium",
        "In 'Resident Evil', only Chris has access to the grenade launcher.",
        "False",
        ["True"])
  ];
}
