// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQjj8bJE2DdiPvHeXYK_DvJP_R6mbQ6KM',
    appId: '1:80089582162:web:14f876c11457214c89ed8b',
    messagingSenderId: '80089582162',
    projectId: 'hale-life-337721',
    authDomain: 'hale-life-337721.firebaseapp.com',
    storageBucket: 'hale-life-337721.appspot.com',
    measurementId: 'G-88RTCWG673',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWfSaEnxVwNx_lRXI3rUi4-7oS8nOirsA',
    appId: '1:80089582162:android:88f70ccce2144e1889ed8b',
    messagingSenderId: '80089582162',
    projectId: 'hale-life-337721',
    storageBucket: 'hale-life-337721.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSWhf-PV5daXjdJXzcMIeSbcJpD4108ew',
    appId: '1:80089582162:ios:d600b2d2587c739389ed8b',
    messagingSenderId: '80089582162',
    projectId: 'hale-life-337721',
    storageBucket: 'hale-life-337721.appspot.com',
    iosBundleId: 'com.example.multiStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSWhf-PV5daXjdJXzcMIeSbcJpD4108ew',
    appId: '1:80089582162:ios:e9dbc2d62186e68889ed8b',
    messagingSenderId: '80089582162',
    projectId: 'hale-life-337721',
    storageBucket: 'hale-life-337721.appspot.com',
    iosBundleId: 'com.example.multiStoreApp.RunnerTests',
  );
}
