// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options1.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXDw-kW3MYDZRBK-OB8x_UQROnxiBIMlY',
    appId: '1:657458233500:web:fd3b9180e8bb4e1456ad59',
    messagingSenderId: '657458233500',
    projectId: 'multi-store-app-ffe5d',
    authDomain: 'multi-store-app-ffe5d.firebaseapp.com',
    storageBucket: 'multi-store-app-ffe5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzaeVvgqI8h8p3242nZHPtc6Vb-zdQB5o',
    appId: '1:657458233500:android:db791f7d4d52f31a56ad59',
    messagingSenderId: '657458233500',
    projectId: 'multi-store-app-ffe5d',
    storageBucket: 'multi-store-app-ffe5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTfQcLGIQwia4ASG7CHPQocMuqEU7_Nic',
    appId: '1:657458233500:ios:ffd424380457beb856ad59',
    messagingSenderId: '657458233500',
    projectId: 'multi-store-app-ffe5d',
    storageBucket: 'multi-store-app-ffe5d.appspot.com',
    iosBundleId: 'com.example.multiStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTfQcLGIQwia4ASG7CHPQocMuqEU7_Nic',
    appId: '1:657458233500:ios:19feb3e9fd93414c56ad59',
    messagingSenderId: '657458233500',
    projectId: 'multi-store-app-ffe5d',
    storageBucket: 'multi-store-app-ffe5d.appspot.com',
    iosBundleId: 'com.example.multiStoreApp.RunnerTests',
  );
}
